version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  api-cuntcock:
    image: api.va-chier.com
    environment:
      - VIRTUAL_HOST=api.cuntcock.com
